### ISSUE TITLE
Error - install windows 7 

### ISSUE THREAD

**Issue by CH1tcg** [ckaznocha/SublimeLinter-contrib-CFLint#23]
Windows 7: 
Straight from the install - SublimeLinter then SublimeLinter-contrib-CFLint

  File "lint.linter in C:\Users\bob\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 349, in get_view_settings
AttributeError: '_thread._local' object has no attribute 'settings'

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "sublime_linter in C:\Users\bob\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 244, in lint
  File "sublime_linter in C:\Users\bob\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 296, in get_linters_for_view
  File "sublime_linter in C:\Users\bob\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 296, in <setcomp>
  File "linter in C:\Users\bob\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-CFLint.sublime-package", line 61, in __init__
  File "lint.linter in C:\Users\bob\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 353, in get_view_settings
RuntimeError: CRITICAL: cflint: Calling 'get_view_settings' outside of lint context

```

**Comment by zspitzer** [comment]
I'm seeing the same on Win10 with an existing install since the sublimeLinter update

**Comment by kaste** [comment]
A 🤞 PR is at #24
