### ISSUE TITLE
Error with SublimeLinter 4

### ISSUE THREAD

**Issue by jhnsctt** [ckaznocha/SublimeLinter-contrib-CFLint#26]
CRITICAL: cflint: Calling 'get_view_settings' outside of lint context

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "sublime_linter in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 263, in lint
  File "sublime_linter in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 323, in get_linters_for_view
  File "sublime_linter in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 323, in <setcomp>
  File "linter in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-CFLint.sublime-package", line 61, in __init__
  File "lint.linter in /Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 360, in get_view_settings
RuntimeError: CRITICAL: cflint: Calling 'get_view_settings' outside of lint context

**Comment by ivanionut** [comment]
Hi @jhnsctt,
I have the same error. Have you found a way to solve it? Thank you.
